<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\Frontend\ViewModel\CurrencyConversion;
use Klevu\Frontend\ViewModel\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Template $block
 * @var CurrencyConversion $currencyConversionViewModel
 * @var Escaper $escaperViewModel
 * @var SecureHtmlRenderer $secureRenderer
 */
$currencyConversionViewModel = $block->getCurrencyConversionViewModel();
$escaperViewModel = $block->getEscaperViewModel();
$escaper = $escaperViewModel->getEscaper();
?>
<?php if ($currencyConversionViewModel->isEnabled()): ?>
    <?php
    $scriptString = <<<script
        if (typeof klevu_uc_userOptions === "undefined") {
            var klevu_uc_userOptions = {};
        }
        klevu_uc_userOptions.priceFormatter = {
            "appendCurrencyAtLast": {$escaper->escapeJs($currencyConversionViewModel->getCurrencyAppendAtLast())},
            "currencySymbol": "{$escaper->escapeJs($currencyConversionViewModel->getCurrencySymbol())}",
            "decimalPlaces": {$escaper->escapeJs($currencyConversionViewModel->getCurrencyPrecision())},
            "decimalSeparator": "{$escaper->escapeJs($currencyConversionViewModel->getCurrencyDecimalSymbol())}",
            "thousandSeparator": "{$escaper->escapeJs($currencyConversionViewModel->getCurrencyGroupSymbol())}",
            "format": "{$escaper->escapeJs($currencyConversionViewModel->getCurrencyFormat())}",
            "grouping": {$escaper->escapeJs($currencyConversionViewModel->getCurrencyGroupLength())},
        };

script;
    ?>
    <?= $secureRenderer->renderTag(
        tagName: 'script',
        attributes: ['type' => 'text/javascript', 'id' => 'klevu_price_formatter'],
        content: $scriptString,
        textContent: false
    ) ?>
<?php endif; ?>
