<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\Frontend\ViewModel\Escaper;
use Klevu\FrontendApi\ViewModel\JsIncludesInterface;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaperViewModel
 * @var JsIncludesInterface $viewModel
 */
$viewModel = $block->getJsIncludesViewModel();
$escaperViewModel = $block->getEscaperViewModel();
$escaper = $escaperViewModel->getEscaper();
?>

<script>
    <?php foreach ($viewModel->getLinks() as $link): ?>
        const script = document.createElement('script');
        script.src = '<?= $escaper->escapeUrl(string: $link) ?>';
        script.type = 'text/javascript';
        document.head.append(script);
    <?php endforeach; ?>
</script>
