<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\Frontend\ViewModel\Escaper;
use Klevu\FrontendApi\ViewModel\JsIncludesInterface;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Template $block
 * @var JsIncludesInterface $viewModel
 * @var Escaper $escaperViewModel
 * @var SecureHtmlRenderer $secureRenderer
 */
$viewModel = $block->getJsIncludesViewModel();
$escaperViewModel = $block->getEscaperViewModel();
$escaper = $escaperViewModel->getEscaper();
?>
<?php foreach ($viewModel->getLinks() as $id => $link): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        tagName: 'script',
        attributes: [
            'type' => 'text/javascript',
            'id' => $escaper->escapeHtmlAttr($id),
            'src' => $escaper->escapeUrl(string: $link),
        ],
        textContent: false,
    ) ?>
<?php endforeach; ?>
