<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

// phpcs:disable SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.MissingVariable

/**
 * @var Template $block
 * @var SecureHtmlRenderer $secureRenderer
 */
?>

<?= /* @noEscape */ $secureRenderer->renderTag(
    tagName: 'script',
    attributes: ['type' => 'text/javascript'],
    content: "\nwindow._klvWebhook = window._klvWebhook|| [];\n",
    textContent: false,
) ?>
