<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\Configuration\Block\Adminhtml\Backend\Template;
use Klevu\Frontend\ViewModel\Escaper as EscaperViewModel;

/**
 * @var Template $block
 * @var EscaperViewModel $escaperViewModel
 */
$escaperViewModel = $block->getData('escaper_view_model');
$escaper = $escaperViewModel->getEscaper();
?>
<section class="admin__page-section">
    <div class="admin__page-section-content" style="display: flex; gap: 20px; margin-left: -10px; margin-right: -10px;">
        <section style="flex-basis: 50%;">
            <h2><?= $escaper->escapeHtml(__('Configuration')->render()) ?></h2>
            <p>
                <?= $escaper->escapeHtml(
                    data: __(
                        'You can find settings to update frontend configuration, under %1Klevu%2 &gt; %1Frontend%2',
                        '<strong>',
                        '</strong>',
                    )->render(),
                    allowedTags: ['strong'],
                ) ?>
            </p>

            <p>
                <?= $escaper->escapeHtml(
                    data: __(
                        'Advanced configuration options can be found under %1Klevu%2 &gt; %1Developer Settings%2 '
                        . '&gt; %1Frontend%2',
                        '<strong>',
                        '</strong>',
                    )->render(),
                    allowedTags: ['strong'],
                ) ?>
            </p>
        </section>

        <section style="flex-basis: 50%;">
            <h2><?= $escaper->escapeHtml(__('Useful Links')->render()) ?></h2>
            <p>
                <?= $escaper->escapeHtml(
                    data: __(
                        'Our %1Documentation%2 contains in-depth guides and articles on the Klevu Frontend. '
                        . 'Some pertinent ones can be found below:',
                        '<a href="https://docs.klevu.com/klevu-magento-v4/frontend-overview" target="_blank">',
                        '</a>',
                    )->render(),
                    allowedTags: ['a'],
                ) ?>
            </p>
            <ul style="margin-left: 20px;">
                <li>
                    <a href="https://docs.klevu.com/klevu-magento-v4/frontend-theme-js-overview"
                       target="_blank"
                       ><?= $escaper->escapeHtml(__('Theme JS Customisation')->render()) ?></a>
                </li>
                <li>
                    <a href="https://docs.klevu.com/klevu-magento-v4/change-search-result-landing-page-srlp-url"
                       target="_blank"
                       ><?= $escaper->escapeHtml(__('Change the search results URL')->render()) ?></a>
                </li>
                <li>
                    <a href="https://docs.klevu.com/klevu-magento-v4/recommendation-widgets"
                       target="_blank"
                       ><?= $escaper->escapeHtml(
                            __('Recommendations Widgets')->render(),
                        ) ?></a>
                </li>
            </ul>
        </section>
    </div>
</section>
